# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0003_usergroup_utime'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='ctime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='utime',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
