# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 03:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0002_business_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='HostToApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('A_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hms.Application')),
                ('h_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hms.Host')),
            ],
        ),
    ]
