# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0003_application_hosttoapp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hosttoapp',
            name='A_obj',
        ),
        migrations.RemoveField(
            model_name='hosttoapp',
            name='h_obj',
        ),
        migrations.AddField(
            model_name='application',
            name='r',
            field=models.ManyToManyField(to='hms.Host'),
        ),
        migrations.DeleteModel(
            name='HostToApp',
        ),
    ]
