# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_auto_20170916_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='utime',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
