# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0004_auto_20170916_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='user_type_id',
            field=models.IntegerField(choices=[(1, '超级管理员'), (2, '管理员'), (3, '普通用户')], default=3),
        ),
    ]
